// Date: 2015/05/27 18:04:51
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package hmggvcutil.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class GVCModelSentry extends ModelBase
{
  //fields
  ModelRenderer Box_0;
  ModelRenderer Box_1;
  ModelRenderer Box_2;
  ModelRenderer Box_3;
  ModelRenderer Box_4;
  ModelRenderer Box_5;
  ModelRenderer Box_6;
  ModelRenderer Box_7;
  ModelRenderer Box_10;
  ModelRenderer Box_11;
  ModelRenderer Box_12;
  ModelRenderer Box_13;
  ModelRenderer Box_14;
  ModelRenderer Box_15;
  ModelRenderer Box_19;
  ModelRenderer Box_20;
  ModelRenderer Box_21;
  ModelRenderer Box_22;
  ModelRenderer Box_23;
  ModelRenderer Box_24;
  ModelRenderer Box_25;
  ModelRenderer Box_26;
  ModelRenderer Box_27;
  ModelRenderer Box_28;
  ModelRenderer Box_29;
  ModelRenderer Box_30;
  ModelRenderer Box_31;
  ModelRenderer Box_32;
  ModelRenderer Box_33;
  ModelRenderer Box_34;
  ModelRenderer Box_35;
  ModelRenderer Box_36;
  ModelRenderer Box_01;

  public GVCModelSentry()
  {
    textureWidth = 128;
    textureHeight = 128;

    Box_0 = new ModelRenderer(this, 85, 21);
    Box_0.addBox(-2F, -10F, -2F, 4, 1, 4);
    Box_0.setRotationPoint(0F, 24F, 0F);
    Box_0.setTextureSize(128, 128);
    Box_0.mirror = true;
    setRotation(Box_0, 0F, 0F, 0F);
    Box_1 = new ModelRenderer(this, 87, 27);
    Box_1.addBox(-1.5F, -8F, -1.5F, 3, 1, 3);
    Box_1.setRotationPoint(0F, 24F, 0F);
    Box_1.setTextureSize(128, 128);
    Box_1.mirror = true;
    setRotation(Box_1, 0F, 0F, 0F);

    Box_2 = new ModelRenderer(this, 77, 21);
    Box_2.addBox(-0.3f, 9.5f, -0.3f, 1, 10, 1);
    Box_2.setRotationPoint(0.5f, 9.5f, 0.5f);
    Box_2.setTextureSize(128, 128);
    Box_2.mirror = true;
    setRotation(Box_2, 0.523599f, 0, 0.523599f);
    Box_3 = new ModelRenderer(this, 77, 21);
    Box_3.addBox(-0.3f, 9.5f, 0.3f, 1, 10, 1);
    Box_3.setRotationPoint(0.5f, 9.5f, -0.5f);
    Box_3.setTextureSize(128, 128);
    Box_3.mirror = true;
    setRotation(Box_3, -0.523599f, 0, 0.523599f);
    Box_4 = new ModelRenderer(this, 77, 21);
    Box_4.addBox(0.3f, 9.5f, -0.3f, 1, 10, 1);
    Box_4.setRotationPoint(-0.5f, 9.5f, 0.5f);
    Box_4.setTextureSize(128, 128);
    Box_4.mirror = true;
    setRotation(Box_4, 0.523599f, 0, -0.523599f);
    Box_5 = new ModelRenderer(this, 77, 21);
    Box_5.addBox(0.3f, 9.5f, 0.3f, 1, 10, 1);
    Box_5.setRotationPoint(-0.5f, 9.5f, -0.5f);
    Box_5.setTextureSize(128, 128);
    Box_5.mirror = true;
    setRotation(Box_5, -0.523599f, 0, -0.523599f);

    Box_6 = new ModelRenderer(this, 90, 17);
    Box_6.addBox(-1F, -11F, -1F, 2, 1, 2);
    Box_6.setRotationPoint(0F, 24F, 0F);
    Box_6.setTextureSize(128, 128);
    Box_6.mirror = true;
    setRotation(Box_6, 0F, 0F, 0F);
    Box_7 = new ModelRenderer(this, 86, 13);
    Box_7.addBox(-2.5F, -12F, -1F, 5, 1, 2);
    Box_7.setRotationPoint(0F, 24F, 0F);
    Box_7.setTextureSize(128, 128);
    Box_7.mirror = true;
    setRotation(Box_7, 0F, 0F, 0F);
    Box_10 = new ModelRenderer(this, 90, 7);
    Box_10.addBox(-2.5F, -15F, -1F, 1, 3, 2);
    Box_10.setRotationPoint(0F, 24F, 0F);
    Box_10.setTextureSize(128, 128);
    Box_10.mirror = true;
    setRotation(Box_10, 0F, 0F, 0F);
    Box_11 = new ModelRenderer(this, 90, 7);
    Box_11.addBox(1.5F, -15F, -1F, 1, 3, 2);
    Box_11.setRotationPoint(0F, 24F, 0F);
    Box_11.setTextureSize(128, 128);
    Box_11.mirror = true;
    setRotation(Box_11, 0F, 0F, 0F);
    Box_12 = new ModelRenderer(this, 59, 35);
    Box_12.addBox(-1F, -2F, -1F, 2, 3, 2);
    Box_12.setRotationPoint(0F, 10F, 0F);
    Box_12.setTextureSize(128, 128);
    Box_12.mirror = true;
    setRotation(Box_12, 0F, 0F, 0F);
    Box_13 = new ModelRenderer(this, 86, 4);
    Box_13.addBox(-3F, -14.5F, -0.5F, 6, 1, 1);
    Box_13.setRotationPoint(0F, 24F, 0F);
    Box_13.setTextureSize(128, 128);
    Box_13.mirror = true;
    setRotation(Box_13, 0F, 0F, 0F);
    Box_14 = new ModelRenderer(this, 43, 37);
    Box_14.addBox(-3F, -3F, -1F, 5, 1, 2);
    Box_14.setRotationPoint(0F, 10F, 0F);
    Box_14.setTextureSize(128, 128);
    Box_14.mirror = true;
    setRotation(Box_14, 0F, 0F, 0F);
    Box_15 = new ModelRenderer(this, 38, 10);
    Box_15.addBox(-1F, -7F, -4F, 2, 4, 13);
    Box_15.setRotationPoint(0F, 9F, 0F);
    Box_15.setTextureSize(128, 128);
    Box_15.mirror = true;
    setRotation(Box_15, 0F, 0F, 0F);
    Box_19 = new ModelRenderer(this, 2, 19);
    Box_19.addBox(-0.5F, -5.5F, -22F, 1, 1, 18);
    Box_19.setRotationPoint(0F, 9F, 0F);
    Box_19.setTextureSize(128, 128);
    Box_19.mirror = true;
    setRotation(Box_19, 0F, 0F, 0F);
    Box_20 = new ModelRenderer(this, 26, 28);
    Box_20.addBox(-1F, -6F, -9F, 2, 2, 5);
    Box_20.setRotationPoint(0F, 9F, 0F);
    Box_20.setTextureSize(128, 128);
    Box_20.mirror = true;
    setRotation(Box_20, 0F, 0F, 0F);
    Box_21 = new ModelRenderer(this, 45, 30);
    Box_21.addBox(-3F, -6F, -1F, 1, 4, 2);
    Box_21.setRotationPoint(0F, 9F, 0F);
    Box_21.setTextureSize(128, 128);
    Box_21.mirror = true;
    setRotation(Box_21, 0F, 0F, 0F);
    Box_22 = new ModelRenderer(this, 52, 32);
    Box_22.addBox(-2F, -6F, -1F, 1, 2, 2);
    Box_22.setRotationPoint(0F, 9F, 0F);
    Box_22.setTextureSize(128, 128);
    Box_22.mirror = true;
    setRotation(Box_22, 0F, 0F, 0F);
    Box_23 = new ModelRenderer(this, 59, 10);
    Box_23.addBox(1F, -5F, -3F, 5, 3, 2);
    Box_23.setRotationPoint(0F, 9F, 0F);
    Box_23.setTextureSize(128, 128);
    Box_23.mirror = true;
    setRotation(Box_23, 0F, 0F, 0F);
    Box_24 = new ModelRenderer(this, 65, 4);
    Box_24.addBox(1F, -6.5F, -3.5F, 1, 1, 3);
    Box_24.setRotationPoint(0F, 9F, 0F);
    Box_24.setTextureSize(128, 128);
    Box_24.mirror = true;
    setRotation(Box_24, 0F, 0F, 0F);
    Box_25 = new ModelRenderer(this, 56, 5);
    Box_25.addBox(1F, -6F, -3F, 2, 1, 2);
    Box_25.setRotationPoint(0F, 9F, 0F);
    Box_25.setTextureSize(128, 128);
    Box_25.mirror = true;
    setRotation(Box_25, 0F, 0F, 0F);
    Box_26 = new ModelRenderer(this, 18, 10);
    Box_26.addBox(-1F, -9F, 2F, 2, 2, 5);
    Box_26.setRotationPoint(0F, 9F, 0F);
    Box_26.setTextureSize(128, 128);
    Box_26.mirror = true;
    setRotation(Box_26, 0F, 0F, 0F);
    Box_27 = new ModelRenderer(this, 18, 12);
    Box_27.addBox(-0.5F, -8.8F, 1.5F, 1, 1, 1);
    Box_27.setRotationPoint(0F, 9F, 0F);
    Box_27.setTextureSize(128, 128);
    Box_27.mirror = true;
    setRotation(Box_27, 0F, 0F, 0F);
    Box_28 = new ModelRenderer(this, 33, 12);
    Box_28.addBox(1F, -6.5F, 3F, 4, 1, 4);
    Box_28.setRotationPoint(0F, 9F, 0F);
    Box_28.setTextureSize(128, 128);
    Box_28.mirror = true;
    setRotation(Box_28, 0F, 0F, 0F);
    Box_29 = new ModelRenderer(this, 37, 5);
    Box_29.addBox(2.5F, -10F, 4F, 2, 4, 2);
    Box_29.setRotationPoint(0F, 9F, 0F);
    Box_29.setTextureSize(128, 128);
    Box_29.mirror = true;
    setRotation(Box_29, 0F, 0F, 0F);
    Box_30 = new ModelRenderer(this, 1, 9);
    Box_30.addBox(-4F, -9F, 4F, 3, 3, 5);
    Box_30.setRotationPoint(0F, 9F, 0F);
    Box_30.setTextureSize(128, 128);
    Box_30.mirror = true;
    setRotation(Box_30, 0F, 0F, 0F);
    Box_31 = new ModelRenderer(this, 1, 2);
    Box_31.addBox(-4F, -9F, 3F, 3, 1, 1);
    Box_31.setRotationPoint(0F, 9F, 0F);
    Box_31.setTextureSize(128, 128);
    Box_31.mirror = true;
    setRotation(Box_31, 0F, 0F, 0F);
    Box_32 = new ModelRenderer(this, 1, 5);
    Box_32.addBox(-3.5F, -10F, 6F, 2, 1, 2);
    Box_32.setRotationPoint(0F, 9F, 0F);
    Box_32.setTextureSize(128, 128);
    Box_32.mirror = true;
    setRotation(Box_32, 0F, 0F, 0F);
    Box_33 = new ModelRenderer(this, 37, 6);
    Box_33.addBox(-0.5F, -8.3F, -35.5F, 1, 0, 37);
    Box_33.setRotationPoint(0F, 9F, 0F);
    Box_33.setTextureSize(128, 128);
    Box_33.mirror = true;
    setRotation(Box_33, 0F, 0F, 0F);
    Box_34 = new ModelRenderer(this, 43, 21);
    Box_34.addBox(-2.5F, -6F, 2F, 2, 1, 1);
    Box_34.setRotationPoint(0F, 9F, 0F);
    Box_34.setTextureSize(128, 128);
    Box_34.mirror = true;
    setRotation(Box_34, 0F, 0F, 0F);
    Box_35 = new ModelRenderer(this, 9, 29);
    Box_35.addBox(0F, -4F, -9F, 0, 2, 4);
    Box_35.setRotationPoint(0F, 9F, 0F);
    Box_35.setTextureSize(128, 128);
    Box_35.mirror = true;
    setRotation(Box_35, 0F, 0F, 0F);
    Box_36 = new ModelRenderer(this, 18, 12);
    Box_36.addBox(-3.5F, -8F, 3.5F, 1, 1, 1);
    Box_36.setRotationPoint(0F, 9F, 0F);
    Box_36.setTextureSize(128, 128);
    Box_36.mirror = true;
    setRotation(Box_36, 0F, 0F, 0F);
    Box_01 = new ModelRenderer(this, 84, 38);
    Box_01.addBox(-2.5F, -9F, -2.5F, 5, 1, 5);
    Box_01.setRotationPoint(0F, 24F, 0F);
    Box_01.setTextureSize(128, 128);
    Box_01.mirror = true;
    setRotation(Box_01, 0F, 0F, 0F);
  }

  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
    //super.render(entity, f, f1, f2, f3, f4, f5);
    this.setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    Box_0.render(par7);
    Box_1.render(par7);
    Box_2.render(par7);//��
    Box_3.render(par7);//��
    Box_4.render(par7);//��
    Box_5.render(par7);//��
    Box_6.render(par7);
    Box_7.render(par7);
    Box_10.render(par7);
    Box_11.render(par7);
    Box_12.render(par7);
    Box_13.render(par7);
    Box_14.render(par7);
    Box_15.render(par7);
    Box_19.render(par7);
    Box_20.render(par7);
    Box_21.render(par7);
    Box_22.render(par7);
    Box_23.render(par7);
    Box_24.render(par7);
    Box_25.render(par7);
    Box_26.render(par7);
    Box_27.render(par7);
    Box_28.render(par7);
    Box_29.render(par7);
    Box_30.render(par7);
    Box_31.render(par7);
    Box_32.render(par7);
    Box_33.render(par7);
    Box_34.render(par7);
    Box_35.render(par7);
    Box_36.render(par7);
    Box_01.render(par7);
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    this.Box_12.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_12.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_13.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_13.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_14.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_14.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_15.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_15.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_19.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_19.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_20.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_20.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_21.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_21.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_22.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_22.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_23.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_23.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_24.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_24.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_25.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_25.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_26.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_26.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_27.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_27.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_28.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_28.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_29.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_29.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_30.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_30.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_31.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_31.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_32.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_32.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_33.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_33.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_34.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_34.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_35.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_35.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Box_36.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Box_36.rotateAngleX = par5 / (180F / (float)Math.PI);

  }

}
