package hmggvcmob.block;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import handmadeguns.HMGAddAttachment;
import handmadeguns.HMGGunMaker;
import handmadeguns.items.guns.HMGItem_Unified_Guns;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.tileentity.TileEntityMobSpawner;
import net.minecraft.util.IIcon;
import net.minecraft.world.World;
import net.minecraft.world.biome.BiomeGenBase;

import java.util.Random;

import static handmadeguns.HandmadeGunsCore.cfg_forceunifiedguns;

public class GVCXBlockFriendCamp extends Block{
    @SideOnly(Side.CLIENT)
    private IIcon TopIcon;

    @SideOnly(Side.CLIENT)
    private IIcon SideIcon;

    public GVCXBlockFriendCamp() {
        super(Material.rock);
        setCreativeTab(CreativeTabs.tabMisc);
        setHardness(1.5F);
        setResistance(1.0F);
        setStepSound(Block.soundTypeStone);
	/*setBlockUnbreakable();
	/*setTickRandomly(true);
	/*disableStats();
        setLightOpacity(1);
        setLightLevel(1.0F);1.0F = 15*/
    }

    @Override
    public boolean onBlockActivated(World world, int x, int y, int z, EntityPlayer player, int side, float posX, float posY, float posZ){
        //world.setBlock(x+3, y+0, z-3, Blocks.fence);
        return true;
    }


    @Override
    public int quantityDropped(Random random){
        return 1;
    }


    @Override
    public void onBlockClicked(World world, int x, int y, int z, EntityPlayer player){
    }

    public boolean renderAsNormalBlock()
    {
        return false;
    }

    public boolean isOpaqueCube()
    {
        return false;
    }

    public void onBlockAdded(World world, int i, int j, int k)
    {
        if(world.getBiomeGenForCoords(i, k) == BiomeGenBase.taiga
                ||world.getBiomeGenForCoords(i, k) == BiomeGenBase.taigaHills
                ||world.getBiomeGenForCoords(i, k) == BiomeGenBase.jungle
                ||world.getBiomeGenForCoords(i, k) == BiomeGenBase.jungleHills){
            world.setBlock(i, j, k, Blocks.air);

        }else{
            j -=2;
            for (int i0 = 0; i0 < 20; ++i0){
                for (int i1 = 0; i1 < 20; ++i1){
                    for (int i2 = 0; i2 < 20; ++i2){
                        world.setBlock(i+i0, j+i1, k+i2, Blocks.air);
                        if(world.getBiomeGenForCoords(i, k) == BiomeGenBase.desert
                                || world.getBiomeGenForCoords(i, k) == BiomeGenBase.desertHills ){
                            world.setBlock(i+i0, j-i1, k+i2, Blocks.sand);
                        }else{
                            world.setBlock(i+i0, j-i1, k+i2, Blocks.dirt);
                        }
                    }
                }
            }
            world.setBlock(i + 0, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 3, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 4, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 11, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 16, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 17, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 0, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 2, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 3, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 4, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 5, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 6, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 7, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 8, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 9, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 10, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 11, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 12, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 13, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 14, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 15, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 16, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 17, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 18, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 0, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 0, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 2, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 3, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 4, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 5, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 6, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 7, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 8, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 9, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 10, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 11, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 12, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 13, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 14, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 15, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 16, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 17, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 18, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 0, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 1, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 3, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 4, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 11, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 16, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 17, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 1, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 2, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 3, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 4, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 5, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 6, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 7, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 8, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 9, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 10, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 11, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 12, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 13, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 14, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 15, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 16, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 17, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 18, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 1, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 1, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 2, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 3, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 4, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 5, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 6, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 7, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 8, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 9, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 10, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 11, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 12, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 13, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 14, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 15, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 16, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 17, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 18, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 1, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 1, j + 3, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 3, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 3, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 3, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 3, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 3, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 3, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 3, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 3, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 3, k + 19, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 4, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 4, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 4, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 4, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 4, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 1, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 3, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 4, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 11, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 16, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 17, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 2, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 2, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 2, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 2, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 3, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 4, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 5, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 6, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 7, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 8, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 9, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 10, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 11, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 12, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 13, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 14, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 15, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 16, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 17, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 2, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 2, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 2, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 2, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 2, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 2, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 2, j + 3, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 4, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 4, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 4, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 4, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 4, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 5, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 5, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 5, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 5, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 5, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 5, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 5, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 5, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 5, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 2, j + 5, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 3, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 3, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 3, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 5, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 6, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 7, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 8, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 9, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 10, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 11, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 12, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 13, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 14, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 15, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 3, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 3, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 3, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 3, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 3, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 3, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 3, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 3, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 3, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 3, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 3, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 3, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 3, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 3, j + 4, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 4, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 5, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 5, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 5, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 5, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 5, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 5, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 5, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 5, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 5, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 5, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 5, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 6, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 6, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 6, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 3, j + 6, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 4, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 4, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 4, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 5, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 6, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 7, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 8, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 9, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 10, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 11, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 12, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 13, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 14, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 15, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 4, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 4, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 4, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 4, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 4, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 4, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 4, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 4, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 4, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 4, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 4, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 4, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 4, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 4, j + 3, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 5, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 5, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 5, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 5, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 5, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 5, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 6, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 6, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 6, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 6, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 6, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 6, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 6, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 6, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 7, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 4, j + 7, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 5, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 5, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 11, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 5, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 5, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 5, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 5, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 5, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 5, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 5, j + 1, k + 5, Blocks.grass);
            world.setBlock(i + 5, j + 1, k + 6, Blocks.grass);
            world.setBlock(i + 5, j + 1, k + 7, Blocks.grass);
            world.setBlock(i + 5, j + 1, k + 8, Blocks.grass);
            world.setBlock(i + 5, j + 1, k + 9, Blocks.grass);
            world.setBlock(i + 5, j + 1, k + 10, Blocks.grass);
            world.setBlock(i + 5, j + 1, k + 11, Blocks.grass);
            world.setBlock(i + 5, j + 1, k + 12, Blocks.grass);
            world.setBlock(i + 5, j + 1, k + 13, Blocks.grass);
            world.setBlock(i + 5, j + 1, k + 14, Blocks.grass);
            world.setBlock(i + 5, j + 1, k + 15, Blocks.grass);
            world.setBlock(i + 5, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 5, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 5, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 5, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 5, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 5, j + 2, k + 5, Blocks.fence);
            world.setBlock(i + 5, j + 2, k + 15, Blocks.fence);
            world.setBlock(i + 5, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 5, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 5, j + 3, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 3, k + 5, Blocks.fence);
            world.setBlock(i + 5, j + 3, k + 15, Blocks.fence);
            world.setBlock(i + 5, j + 4, k + 5, Blocks.fence);
            world.setBlock(i + 5, j + 4, k + 15, Blocks.fence);
            world.setBlock(i + 5, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 5, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 5, k + 5, Blocks.fence);
            world.setBlock(i + 5, j + 5, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 5, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 5, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 5, k + 15, Blocks.fence);
            world.setBlock(i + 5, j + 5, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 6, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 6, k + 5, Blocks.fence);
            world.setBlock(i + 5, j + 6, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 6, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 6, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 6, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 6, k + 15, Blocks.fence);
            world.setBlock(i + 5, j + 6, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 7, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 7, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 7, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 7, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 7, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 5, j + 7, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 6, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 6, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 11, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 6, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 6, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 6, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 6, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 6, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 6, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 6, j + 1, k + 5, Blocks.grass);
            world.setBlock(i + 6, j + 1, k + 6, Blocks.grass);
            world.setBlock(i + 6, j + 1, k + 7, Blocks.grass);
            world.setBlock(i + 6, j + 1, k + 8, Blocks.grass);
            world.setBlock(i + 6, j + 1, k + 9, Blocks.grass);
            world.setBlock(i + 6, j + 1, k + 10, Blocks.grass);
            world.setBlock(i + 6, j + 1, k + 11, Blocks.grass);
            world.setBlock(i + 6, j + 1, k + 12, Blocks.grass);
            world.setBlock(i + 6, j + 1, k + 13, Blocks.grass);
            world.setBlock(i + 6, j + 1, k + 14, Blocks.grass);
            world.setBlock(i + 6, j + 1, k + 15, Blocks.grass);
            world.setBlock(i + 6, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 6, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 6, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 6, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 6, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 6, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 6, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 6, j + 3, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 4, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 4, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 4, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 5, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 5, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 5, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 5, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 6, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 6, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 6, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 6, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 6, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 6, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 6, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 6, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 7, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 7, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 6, j + 9, k + 12, Blocks.iron_bars);
            world.setBlock(i + 7, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 7, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 7, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 11, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 7, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 7, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 7, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 7, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 7, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 7, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 7, j + 1, k + 5, Blocks.grass);
            world.setBlock(i + 7, j + 1, k + 6, Blocks.grass);
            world.setBlock(i + 7, j + 1, k + 7, Blocks.grass);
            world.setBlock(i + 7, j + 1, k + 8, Blocks.grass);
            world.setBlock(i + 7, j + 1, k + 9, Blocks.grass);
            world.setBlock(i + 7, j + 1, k + 10, Blocks.grass);
            world.setBlock(i + 7, j + 1, k + 11, Blocks.grass);
            world.setBlock(i + 7, j + 1, k + 12, Blocks.dirt);
            world.setBlock(i + 7, j + 1, k + 13, Blocks.grass);
            world.setBlock(i + 7, j + 1, k + 14, Blocks.grass);
            world.setBlock(i + 7, j + 1, k + 15, Blocks.grass);
            world.setBlock(i + 7, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 7, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 7, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 7, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 7, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 7, j + 2, k + 10, Blocks.air);
            world.setBlock(i + 7, j + 2, k + 12, Blocks.iron_block);
            world.setBlock(i + 7, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 7, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 7, j + 3, k + 12, Blocks.iron_bars);
            world.setBlock(i + 7, j + 3, k + 19, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 4, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 4, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 4, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 4, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 4, k + 12, Blocks.iron_bars);
            world.setBlock(i + 7, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 5, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 5, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 5, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 5, k + 12, Blocks.iron_bars);
            world.setBlock(i + 7, j + 5, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 5, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 6, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 6, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 6, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 6, k + 12, Blocks.iron_bars);
            world.setBlock(i + 7, j + 6, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 6, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 6, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 7, j + 7, k + 12, Blocks.iron_bars);
            world.setBlock(i + 7, j + 8, k + 12, Blocks.iron_bars);
            world.setBlock(i + 7, j + 9, k + 11, Blocks.iron_bars);
            world.setBlock(i + 7, j + 9, k + 12, Blocks.iron_bars);
            world.setBlock(i + 7, j + 9, k + 13, Blocks.iron_bars);
            world.setBlock(i + 8, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 8, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 8, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 11, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 8, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 8, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 8, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 8, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 8, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 8, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 8, j + 1, k + 5, Blocks.grass);
            world.setBlock(i + 8, j + 1, k + 6, Blocks.grass);
            world.setBlock(i + 8, j + 1, k + 7, Blocks.grass);
            world.setBlock(i + 8, j + 1, k + 8, Blocks.grass);
            world.setBlock(i + 8, j + 1, k + 9, Blocks.grass);
            world.setBlock(i + 8, j + 1, k + 10, Blocks.grass);
            world.setBlock(i + 8, j + 1, k + 11, Blocks.grass);
            world.setBlock(i + 8, j + 1, k + 12, Blocks.grass);
            world.setBlock(i + 8, j + 1, k + 13, Blocks.grass);
            world.setBlock(i + 8, j + 1, k + 14, Blocks.grass);
            world.setBlock(i + 8, j + 1, k + 15, Blocks.grass);
            world.setBlock(i + 8, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 8, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 8, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 8, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 8, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 8, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 8, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 8, j + 3, k + 19, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 4, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 4, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 4, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 4, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 5, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 5, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 5, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 5, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 5, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 5, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 5, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 5, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 6, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 6, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 6, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 6, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 8, j + 9, k + 12, Blocks.iron_bars);
            world.setBlock(i + 9, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 9, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 9, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 9, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 9, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 9, j + 0, k + 5, Blocks.grass);
            world.setBlock(i + 9, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 9, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 9, j + 0, k + 8, Blocks.chest);
            world.setBlock(i + 9, j + 0, k + 9, Blocks.chest);
            world.setBlock(i + 9, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 9, j + 0, k + 11, Blocks.chest);
            world.setBlock(i + 9, j + 0, k + 12, Blocks.chest);
            TileEntityChest Chest;
            TileEntityChest Chest2;
            Chest  = (TileEntityChest) world.getTileEntity(i + 9, j + 0, k + 8);
            Chest2 = (TileEntityChest) world.getTileEntity(i + 9, j + 0, k + 11);
            for (int s = 0; s < 36; ++s){
                int suro = s;
                Item gun = (Item) HMGGunMaker.Guns.get(new Random().nextInt(HMGGunMaker.Guns.size()));
                if(cfg_forceunifiedguns){
                    if(gun instanceof HMGItem_Unified_Guns && !((HMGItem_Unified_Guns) gun).gunInfo.isinRoot){
                        gun = null;
                    }
                }
                if(gun != null) Chest.setInventorySlotContents(suro, new ItemStack(gun));
            }
            for (int s = 0; s < 36; ++s){
                int suro = s;
                Item gun = (Item) HMGGunMaker.Guns.get(new Random().nextInt(HMGGunMaker.Guns.size()));
                if(cfg_forceunifiedguns){
                    if(gun instanceof HMGItem_Unified_Guns && !((HMGItem_Unified_Guns) gun).gunInfo.isinRoot){
                        gun = null;
                    }
                }
                if(gun != null) Chest2.setInventorySlotContents(suro, new ItemStack(gun));
            }
            world.setBlock(i + 9, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 9, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 9, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 9, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 9, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 9, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 9, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 9, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 9, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 9, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 9, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 9, j + 1, k + 8, Blocks.chest);
            world.setBlock(i + 9, j + 1, k + 9, Blocks.chest);
            world.setBlock(i + 9, j + 1, k + 10, Blocks.grass);
            world.setBlock(i + 9, j + 1, k + 11, Blocks.chest);
            world.setBlock(i + 9, j + 1, k + 12, Blocks.chest);
            TileEntityChest Chest3;
            TileEntityChest Chest4;
            Chest3  = (TileEntityChest) world.getTileEntity(i + 9, j + 1, k + 8);
            Chest4 = (TileEntityChest) world.getTileEntity(i + 9, j + 1, k + 11);
            for (int s = 0; s < 18; ++s){
                int suro = s;
                Chest3.setInventorySlotContents(suro, new ItemStack((Item) HMGAddAttachment.Magazines.get(new Random().nextInt(HMGAddAttachment.Magazines.size())),5));
                Chest4.setInventorySlotContents(suro, new ItemStack((Item) HMGAddAttachment.Attach.get(new Random().nextInt(HMGAddAttachment.Attach.size()))));
            }
            world.setBlock(i + 9, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 9, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 9, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 9, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 9, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 9, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 9, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 9, j + 3, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 4, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 4, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 4, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 4, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 4, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 5, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 5, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 5, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 5, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 5, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 5, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 5, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 5, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 5, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 5, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 9, j + 6, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 10, j, k + 0, Blocks.dirt);
            world.setBlock(i + 10, j, k + 1, Blocks.dirt);
            world.setBlock(i + 10, j, k + 2, Blocks.dirt);
            world.setBlock(i + 10, j, k + 3, Blocks.grass);
            world.setBlock(i + 10, j, k + 4, Blocks.grass);
            world.setBlock(i + 10, j, k + 5, Blocks.dirt);
            world.setBlock(i + 10, j, k + 6, Blocks.dirt);
            world.setBlock(i + 10, j, k + 7, Blocks.dirt);
            world.setBlock(i + 10, j, k + 8, Blocks.bed , 0 , 3);
            world.setBlock(i + 10, j, k + 9, Blocks.bed , 8 , 3);
            world.setBlock(i + 10, j, k + 10, Blocks.fence);
            world.setBlock(i + 10, j, k + 11, Blocks.bed , 0 , 3);
            world.setBlock(i + 10, j, k + 12, Blocks.bed , 8 , 3);
            world.setBlock(i + 10, j, k + 13, Blocks.dirt);
            world.setBlock(i + 10, j, k + 14, Blocks.grass);
            world.setBlock(i + 10, j, k + 15, Blocks.grass);
            world.setBlock(i + 10, j, k + 16, Blocks.grass);
            world.setBlock(i + 10, j, k + 17, Blocks.grass);
            world.setBlock(i + 10, j, k + 18, Blocks.dirt);
            world.setBlock(i + 10, j, k + 19, Blocks.dirt);
            world.setBlock(i + 10, j, k + 20, Blocks.dirt);
            world.setBlock(i + 10, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 10, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 10, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 10, j + 1, k + 10, Blocks.fence);
            world.setBlock(i + 10, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 10, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 10, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 10, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 10, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 10, j + 2, k + 10, Blocks.fence);
            world.setBlock(i + 10, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 10, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 10, j + 3, k + 10, Blocks.fence);
            world.setBlock(i + 10, j + 4, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 4, k + 10, Blocks.fence);
            world.setBlock(i + 10, j + 4, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 5, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 5, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 5, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 5, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 5, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 5, k + 10, Blocks.fence);
            world.setBlock(i + 10, j + 5, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 5, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 5, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 5, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 5, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 6, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 6, k + 10, Blocks.fence);
            world.setBlock(i + 10, j + 6, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 10, j + 7, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 11, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 11, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 11, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 11, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 11, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 11, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 11, j + 0, k + 7, Blocks.grass);
            world.setBlock(i + 11, j + 0, k + 8, Blocks.bed , 3 , 3);
            world.setBlock(i + 11, j + 0, k + 9, Blocks.air );
            world.setBlock(i + 11, j + 0, k + 10, Blocks.bed , 3 , 3);
            world.setBlock(i + 11, j + 0, k + 11, Blocks.air );
            world.setBlock(i + 11, j + 0, k + 12, Blocks.bed , 3 , 3);
            world.setBlock(i + 12, j + 0, k + 8, Blocks.bed , 11 , 3);
            world.setBlock(i + 12, j + 0, k + 9, Blocks.mob_spawner, 2, 2 );
            TileEntityMobSpawner tileentitymobspawner = (TileEntityMobSpawner)world.getTileEntity(i + 12, j + 0, k + 9);

            if (tileentitymobspawner != null)
            {
                tileentitymobspawner.func_145881_a().setEntityName("GVCMob.SysSpawnSoldier");
            }
            world.setBlock(i + 12, j + 0, k + 10, Blocks.bed , 11 , 3);
            world.setBlock(i + 12, j + 0, k + 11, Blocks.mob_spawner, 2, 2);
            tileentitymobspawner = (TileEntityMobSpawner)world.getTileEntity(i + 12, j + 0, k + 11);

            if (tileentitymobspawner != null)
            {
                tileentitymobspawner.func_145881_a().setEntityName("GVCMob.SysSpawnSoldier");
            }
            world.setBlock(i + 12, j + 0, k + 12, Blocks.bed , 11 , 3);
            world.setBlock(i + 11, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 11, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 11, j + 0, k + 15, Blocks.grass);
            world.setBlock(i + 11, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 11, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 11, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 11, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 11, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 11, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 11, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 11, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 11, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 11, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 11, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 11, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 11, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 11, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 11, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 11, j + 4, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 4, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 4, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 4, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 4, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 5, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 5, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 5, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 5, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 5, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 5, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 5, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 5, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 5, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 5, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 11, j + 6, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 12, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 12, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 12, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 12, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 12, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 12, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 12, j + 0, k + 7, Blocks.grass);
            world.setBlock(i + 12, j + 0, k + 13, Blocks.grass);
            world.setBlock(i + 12, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 12, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 12, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 12, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 12, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 12, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 12, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 12, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 12, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 12, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 12, j + 1, k + 5, Blocks.grass);
            world.setBlock(i + 12, j + 1, k + 6, Blocks.grass);
            world.setBlock(i + 12, j + 1, k + 13, Blocks.dirt);
            world.setBlock(i + 12, j + 1, k + 14, Blocks.dirt);
            world.setBlock(i + 12, j + 1, k + 15, Blocks.dirt);
            world.setBlock(i + 12, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 12, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 12, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 12, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 12, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 12, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 12, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 12, j + 3, k + 19, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 4, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 4, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 4, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 4, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 4, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 5, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 5, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 5, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 5, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 5, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 5, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 5, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 6, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 6, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 6, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 12, j + 6, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 13, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 13, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 13, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 13, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 13, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 13, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 13, j + 0, k + 7, Blocks.grass);
            world.setBlock(i + 13, j + 0, k + 8, Blocks.grass);
            world.setBlock(i + 13, j + 0, k + 9, Blocks.grass);
            world.setBlock(i + 13, j + 0, k + 10, Blocks.grass);
            world.setBlock(i + 13, j + 0, k + 11, Blocks.grass);
            world.setBlock(i + 13, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 13, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 13, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 13, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 13, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 13, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 13, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 13, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 13, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 13, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 13, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 13, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 13, j + 1, k + 5, Blocks.grass);
            world.setBlock(i + 13, j + 1, k + 6, Blocks.grass);
            world.setBlock(i + 13, j + 1, k + 12, Blocks.grass);
            world.setBlock(i + 13, j + 1, k + 13, Blocks.grass);
            world.setBlock(i + 13, j + 1, k + 14, Blocks.grass);
            world.setBlock(i + 13, j + 1, k + 15, Blocks.grass);
            world.setBlock(i + 13, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 13, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 13, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 13, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 13, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 13, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 13, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 13, j + 3, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 3, k + 19, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 4, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 4, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 4, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 4, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 5, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 5, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 5, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 5, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 5, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 5, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 6, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 6, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 6, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 6, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 6, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 13, j + 6, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 14, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 14, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 11, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 14, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 14, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 14, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 14, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 14, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 14, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 14, j + 1, k + 5, Blocks.grass);
            world.setBlock(i + 14, j + 1, k + 6, Blocks.grass);
            world.setBlock(i + 14, j + 1, k + 7, Blocks.grass);
            world.setBlock(i + 14, j + 1, k + 8, Blocks.grass);
            world.setBlock(i + 14, j + 1, k + 12, Blocks.grass);
            world.setBlock(i + 14, j + 1, k + 13, Blocks.grass);
            world.setBlock(i + 14, j + 1, k + 14, Blocks.grass);
            world.setBlock(i + 14, j + 1, k + 15, Blocks.grass);
            world.setBlock(i + 14, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 14, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 14, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 14, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 14, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 14, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 14, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 14, j + 3, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 4, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 4, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 4, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 4, k + 19, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 5, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 5, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 5, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 5, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 6, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 6, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 6, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 6, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 6, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 6, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 6, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 6, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 7, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 14, j + 7, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 15, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 15, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 10, Blocks.grass);
            world.setBlock(i + 15, j + 0, k + 11, Blocks.grass);
            world.setBlock(i + 15, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 15, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 15, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 15, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 15, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 15, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 15, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 15, j + 1, k + 5, Blocks.grass);
            world.setBlock(i + 15, j + 1, k + 6, Blocks.grass);
            world.setBlock(i + 15, j + 1, k + 7, Blocks.grass);
            world.setBlock(i + 15, j + 1, k + 8, Blocks.grass);
            world.setBlock(i + 15, j + 1, k + 12, Blocks.grass);
            world.setBlock(i + 15, j + 1, k + 13, Blocks.grass);
            world.setBlock(i + 15, j + 1, k + 14, Blocks.grass);
            world.setBlock(i + 15, j + 1, k + 15, Blocks.grass);
            world.setBlock(i + 15, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 15, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 15, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 15, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 15, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 15, j + 2, k + 5, Blocks.fence);
            world.setBlock(i + 15, j + 2, k + 15, Blocks.fence);
            world.setBlock(i + 15, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 15, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 15, j + 3, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 3, k + 5, Blocks.fence);
            world.setBlock(i + 15, j + 3, k + 15, Blocks.fence);
            world.setBlock(i + 15, j + 4, k + 5, Blocks.fence);
            world.setBlock(i + 15, j + 4, k + 15, Blocks.fence);
            world.setBlock(i + 15, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 5, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 5, k + 5, Blocks.fence);
            world.setBlock(i + 15, j + 5, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 5, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 5, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 5, k + 15, Blocks.fence);
            world.setBlock(i + 15, j + 5, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 6, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 6, k + 5, Blocks.fence);
            world.setBlock(i + 15, j + 6, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 6, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 6, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 6, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 6, k + 15, Blocks.fence);
            world.setBlock(i + 15, j + 6, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 7, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 7, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 7, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 7, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 7, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 15, j + 7, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 16, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 16, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 16, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 5, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 6, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 7, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 8, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 9, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 10, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 11, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 12, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 13, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 14, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 15, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 16, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 16, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 16, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 16, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 16, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 16, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 16, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 16, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 16, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 16, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 16, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 16, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 16, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 16, j + 4, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 5, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 5, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 5, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 5, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 5, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 6, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 6, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 6, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 6, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 6, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 6, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 6, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 6, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 7, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 16, j + 7, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 17, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 17, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 17, j + 0, k + 3, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 4, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 5, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 6, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 7, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 8, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 9, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 10, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 11, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 12, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 13, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 14, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 15, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 16, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 17, Blocks.grass);
            world.setBlock(i + 17, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 17, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 17, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 17, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 17, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 17, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 17, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 17, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 17, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 17, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 17, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 17, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 17, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 17, j + 4, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 5, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 5, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 5, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 5, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 5, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 5, k + 10, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 5, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 5, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 5, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 5, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 5, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 6, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 6, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 6, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 17, j + 6, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 3, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 4, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 11, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 16, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 17, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 18, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 18, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 18, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 18, j + 1, k + 2, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 3, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 4, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 5, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 6, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 7, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 8, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 9, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 10, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 11, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 12, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 13, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 14, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 15, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 16, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 17, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 18, Blocks.planks);
            world.setBlock(i + 18, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 18, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 18, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 18, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 18, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 18, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 18, j + 3, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 3, k + 19, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 3, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 4, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 7, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 8, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 9, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 11, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 12, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 16, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 17, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 4, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 5, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 5, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 5, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 5, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 18, j + 5, k + 15, Blocks.leaves,12,3);
            world.setBlock(i + 19, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 3, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 4, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 11, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 16, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 17, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 19, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 2, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 3, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 4, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 5, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 6, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 7, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 8, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 9, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 10, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 11, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 12, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 13, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 14, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 15, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 16, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 17, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 18, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 19, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 19, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 2, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 3, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 4, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 5, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 6, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 7, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 8, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 9, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 10, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 11, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 12, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 13, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 14, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 15, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 16, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 17, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 18, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 19, j + 2, k + 20, Blocks.grass);
            world.setBlock(i + 19, j + 3, k + 1, Blocks.leaves,12,3);
            world.setBlock(i + 19, j + 3, k + 2, Blocks.leaves,12,3);
            world.setBlock(i + 19, j + 3, k + 5, Blocks.leaves,12,3);
            world.setBlock(i + 19, j + 3, k + 6, Blocks.leaves,12,3);
            world.setBlock(i + 19, j + 3, k + 13, Blocks.leaves,12,3);
            world.setBlock(i + 19, j + 3, k + 14, Blocks.leaves,12,3);
            world.setBlock(i + 19, j + 3, k + 18, Blocks.leaves,12,3);
            world.setBlock(i + 20, j + 0, k + 0, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 1, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 2, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 3, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 4, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 5, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 6, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 7, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 8, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 9, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 10, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 11, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 12, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 13, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 14, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 15, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 16, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 17, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 18, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 19, Blocks.dirt);
            world.setBlock(i + 20, j + 0, k + 20, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 0, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 1, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 2, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 3, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 4, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 5, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 6, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 7, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 8, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 9, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 10, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 11, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 12, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 13, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 14, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 15, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 16, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 17, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 18, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 19, Blocks.dirt);
            world.setBlock(i + 20, j + 1, k + 20, Blocks.dirt);
            world.setBlock(i + 20, j + 2, k + 0, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 1, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 2, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 3, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 4, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 5, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 6, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 7, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 8, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 9, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 10, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 11, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 12, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 13, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 14, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 15, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 16, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 17, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 18, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 19, Blocks.grass);
            world.setBlock(i + 20, j + 2, k + 20, Blocks.grass);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 3, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 4, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 5, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 6, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 7, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 8, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 9, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 10, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 11, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 12, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 13, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 14, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 15, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 16, 5, 2);
            world.setBlockMetadataWithNotify(i + 3, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 4, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 4, j + 1, k + 4, 5, 2);
            world.setBlockMetadataWithNotify(i + 4, j + 1, k + 7, 5, 2);
            world.setBlockMetadataWithNotify(i + 4, j + 1, k + 10, 5, 2);
            world.setBlockMetadataWithNotify(i + 4, j + 1, k + 13, 5, 2);
            world.setBlockMetadataWithNotify(i + 4, j + 1, k + 16, 5, 2);
            world.setBlockMetadataWithNotify(i + 4, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 5, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 5, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 6, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 6, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 7, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 7, j + 1, k + 4, 5, 2);
            world.setBlockMetadataWithNotify(i + 7, j + 1, k + 16, 5, 2);
            world.setBlockMetadataWithNotify(i + 7, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 7, j + 2, k + 7, 5, 2);
            world.setBlock( i + 7, j + 2, k + 11, Blocks.redstone_wire);
            world.setBlockMetadataWithNotify(i + 7, j + 2, k + 13, 5, 2);
            world.setBlockMetadataWithNotify(i + 8, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 8, j + 1, k + 17, 2, 2);
            world.setBlock( i + 8, j + 2, k + 10, Blocks.redstone_wire);
            world.setBlock( i + 8, j + 2, k + 11, Blocks.redstone_wire);
            world.setBlockMetadataWithNotify(i + 9, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 9, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 10, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 10, j + 1, k + 4, 5, 2);
            world.setBlockMetadataWithNotify(i + 10, j + 1, k + 7, 5, 2);
            world.setBlockMetadataWithNotify(i + 10, j + 1, k + 13, 5, 2);
            world.setBlockMetadataWithNotify(i + 10, j + 1, k + 16, 5, 2);
            world.setBlockMetadataWithNotify(i + 10, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 11, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 11, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 12, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 12, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 13, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 13, j + 1, k + 4, 5, 2);
            world.setBlockMetadataWithNotify(i + 13, j + 1, k + 7, 5, 2);
            world.setBlockMetadataWithNotify(i + 13, j + 1, k + 10, 5, 2);
            world.setBlockMetadataWithNotify(i + 13, j + 1, k + 16, 5, 2);
            world.setBlockMetadataWithNotify(i + 13, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 13, j + 2, k + 13, 5, 2);
            world.setBlockMetadataWithNotify(i + 14, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 14, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 15, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 15, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 16, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 16, j + 1, k + 4, 5, 2);
            world.setBlockMetadataWithNotify(i + 16, j + 1, k + 7, 5, 2);
            world.setBlockMetadataWithNotify(i + 16, j + 1, k + 10, 5, 2);
            world.setBlockMetadataWithNotify(i + 16, j + 1, k + 13, 5, 2);
            world.setBlockMetadataWithNotify(i + 16, j + 1, k + 16, 5, 2);
            world.setBlockMetadataWithNotify(i + 16, j + 1, k + 17, 2, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 3, 3, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 4, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 5, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 6, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 7, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 8, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 9, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 10, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 11, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 12, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 13, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 14, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 15, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 16, 4, 2);
            world.setBlockMetadataWithNotify(i + 17, j + 1, k + 17, 2, 2);
        }//if end
        //end
    }
}
