// Date: 2014/04/12 16:37:15
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package hmggvcmob.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class GVCModelGK extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
  
  public GVCModelGK()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(-2F, -2F, -6F, 4, 16, 4);
      Shape1.setRotationPoint(-6F, 10F, 2F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(-2F, -2F, -6F, 4, 16, 4);
      Shape2.setRotationPoint(6F, 10F, 2F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 21);
      Shape3.addBox(0F, 0F, 0F, 6, 12, 4);
      Shape3.setRotationPoint(-9F, 0F, 4F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 21);
      Shape4.addBox(0F, 0F, 0F, 6, 12, 4);
      Shape4.setRotationPoint(3F, 0F, 4F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 16, 0);
      Shape5.addBox(-2F, 13F, -10F, 4, 1, 4);
      Shape5.setRotationPoint(-6F, 10F, 2F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 16, 0);
      Shape6.addBox(-2F, 13F, -10F, 4, 1, 4);
      Shape6.setRotationPoint(6F, 10F, 2F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);

      Shape7 = new ModelRenderer(this, 16, 6);
      Shape7.addBox(0F, 0F, 0F, 6, 3, 8);
      Shape7.setRotationPoint(-9F, 0F, 0F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 16, 6);
      Shape8.addBox(0F, 0F, 0F, 6, 3, 8);
      Shape8.setRotationPoint(3F, 0F, 0F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 38);
      Shape9.addBox(0F, 0F, 0F, 4, 4, 8);
      Shape9.setRotationPoint(-2F, 0F, -4F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 33, 0);
      Shape10.addBox(0F, 0F, 0F, 6, 1, 2);
      Shape10.setRotationPoint(-3F, 1F, 1F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 25, 38);
      Shape11.addBox(0F, 0F, 0F, 2, 2, 10);
      Shape11.setRotationPoint(-1F, -3F, -5F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, -0.4363323F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 0, 51);
      Shape12.addBox(0F, 0F, 0F, 12, 4, 8);
      Shape12.setRotationPoint(-6F, -6F, -8F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 40, 51);
      Shape13.addBox(0F, 0F, 0F, 4, 4, 4);
      Shape13.setRotationPoint(-2F, -6F, -12F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 21, 21);
      Shape14.addBox(0F, 0F, 0F, 4, 4, 4);
      Shape14.setRotationPoint(-8F, 8F, 0F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 21, 21);
      Shape15.addBox(0F, 0F, 0F, 4, 4, 4);
      Shape15.setRotationPoint(4F, 8F, 0F);
      Shape15.setTextureSize(64, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 0, 64);
      Shape16.addBox(0F, 0F, 0F, 2, 2, 6);
      Shape16.setRotationPoint(-8F, -6F, -6F);
      Shape16.setTextureSize(64, 32);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 17, 64);
      Shape17.addBox(-1.5F, 0F, -4F, 3, 3, 8);
      Shape17.setRotationPoint(-7F, -9F, -3F);
      Shape17.setTextureSize(64, 32);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 40, 64);
      Shape18.addBox(0F, 0F, -12F, 1, 1, 8);
      Shape18.setRotationPoint(-7.5F, -8F, -3F);
      Shape18.setTextureSize(64, 32);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 59, 64);
      Shape19.addBox(0F, 0F, -4F, 1, 1, 1);
      Shape19.setRotationPoint(-7.5F, -10F, -3F);
      Shape19.setTextureSize(64, 128);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 0, 76);
      Shape20.addBox(-2.0F, 0F, -2.0F, 4, 2, 4);
      Shape20.setRotationPoint(2F, -8F, -4F);
      Shape20.setTextureSize(64, 128);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 17, 76);
      Shape21.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape21.setRotationPoint(4F, -10F, -1F);
      Shape21.setTextureSize(64, 128);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
      this.setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    Shape1.render(par7);
    Shape2.render(par7);
    Shape3.render(par7);
    Shape4.render(par7);
    Shape5.render(par7);
    Shape6.render(par7);
    Shape7.render(par7);
    Shape8.render(par7);
    Shape9.render(par7);
    Shape10.render(par7);
    Shape11.render(par7);
    Shape12.render(par7);
    Shape13.render(par7);
    Shape14.render(par7);
    Shape15.render(par7);
    Shape16.render(par7);
    Shape17.render(par7);
    Shape18.render(par7);
    Shape19.render(par7);
    Shape20.render(par7);
    Shape21.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
	  this.Shape17.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Shape17.rotateAngleX = par5 / (180F / (float)Math.PI);
      
      this.Shape18.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Shape18.rotateAngleX = par5 / (180F / (float)Math.PI);
      
      this.Shape19.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Shape19.rotateAngleX = par5 / (180F / (float)Math.PI);
      
      this.Shape20.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Shape20.rotateAngleX = par5 / (180F / (float)Math.PI);
	  
      this.Shape1.rotateAngleX = -1.5F * this.func_78172_a(par1, 13.0F) * par2;
      this.Shape2.rotateAngleX = 1.5F * this.func_78172_a(par1, 13.0F) * par2;
      this.Shape1.rotateAngleY = 0.0F;
      this.Shape2.rotateAngleY = 0.0F;
      
      this.Shape5.rotateAngleX = -1.5F * this.func_78172_a(par1, 13.0F) * par2;
      this.Shape6.rotateAngleX = 1.5F * this.func_78172_a(par1, 13.0F) * par2;
      this.Shape5.rotateAngleY = 0.0F;
      this.Shape6.rotateAngleY = 0.0F;
	  
	  
    //super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

  private float func_78172_a(float par1, float par2)
  {
      return (Math.abs(par1 % par2 - par2 * 0.5F) - par2 * 0.25F) / (par2 * 0.25F);
  }

}
