// Date: 2015/06/12 20:43:03
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package hmggvcmob.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class GVCModelSoldierTank extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
  
  public GVCModelSoldierTank()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 8, 4, 19);
      Shape1.setRotationPoint(-4F, 19F, -8F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 54, 0);
      Shape2.addBox(0F, 0F, 0F, 3, 5, 15);
      Shape2.setRotationPoint(-7F, 19F, -9F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 88, 0);
      Shape3.addBox(0F, 0F, 0F, 3, 6, 6);
      Shape3.setRotationPoint(-7F, 18F, 6F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 107, 0);
      Shape4.addBox(0F, 0F, 0F, 3, 4, 2);
      Shape4.setRotationPoint(-7F, 19F, -11F);
      Shape4.setTextureSize(128, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 54, 0);
      Shape5.addBox(0F, 0F, 0F, 3, 5, 15);
      Shape5.setRotationPoint(4F, 19F, -9F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 88, 0);
      Shape6.addBox(0F, 0F, 0F, 3, 6, 6);
      Shape6.setRotationPoint(4F, 18F, 6F);
      Shape6.setTextureSize(128, 128);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 107, 0);
      Shape7.addBox(0F, 0F, -2F, 3, 4, 2);
      Shape7.setRotationPoint(4F, 19F, -9F);
      Shape7.setTextureSize(128, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 106, 8);
      Shape8.addBox(0F, 0F, 0F, 8, 3, 3);
      Shape8.setRotationPoint(-4F, 20F, -11F);
      Shape8.setTextureSize(128, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0.3490659F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 25);
      Shape9.addBox(-5F, -2F, -5F, 10, 4, 11);
      Shape9.setRotationPoint(0F, 17F, 1F);
      Shape9.setTextureSize(128, 128);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 42, 25);
      Shape10.addBox(-4F, -2F, -6F, 8, 4, 1);
      Shape10.setRotationPoint(0F, 17F, 1F);
      Shape10.setTextureSize(128, 128);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 42, 32);
      Shape11.addBox(-3F, -1F, -7F, 6, 3, 1);
      Shape11.setRotationPoint(0F, 17F, 1F);
      Shape11.setTextureSize(128, 128);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 61, 24);
      Shape12.addBox(-4F, -2F, 6F, 8, 3, 3);
      Shape12.setRotationPoint(0F, 17F, 1F);
      Shape12.setTextureSize(128, 128);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 84, 24);
      Shape13.addBox(-6F, -1F, -4F, 1, 3, 9);
      Shape13.setRotationPoint(0F, 17F, 1F);
      Shape13.setTextureSize(128, 128);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 84, 24);
      Shape14.addBox(5F, -1F, -4F, 1, 3, 9);
      Shape14.setRotationPoint(0F, 17F, 0F);
      Shape14.setTextureSize(128, 128);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 0, 42);
      Shape15.addBox(-1F, -1F, -18F, 2, 2, 12);
      Shape15.setRotationPoint(0F, 17F, 1F);
      Shape15.setTextureSize(128, 128);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 0, 60);
      Shape16.addBox(2F, -3F, 0F, 2, 1, 2);
      Shape16.setRotationPoint(0F, 17F, 1F);
      Shape16.setTextureSize(128, 128);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 0, 60);
      Shape17.addBox(-4F, -3F, 0F, 2, 1, 2);
      Shape17.setRotationPoint(0F, 17F, 1F);
      Shape17.setTextureSize(128, 128);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 9, 60);
      Shape18.addBox(-4F, -3F, -3F, 2, 1, 2);
      Shape18.setRotationPoint(0F, 17F, 1F);
      Shape18.setTextureSize(128, 128);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 79, 31);
      Shape19.addBox(3F, -6F, 4F, 1, 4, 1);
      Shape19.setRotationPoint(0F, 17F, 1F);
      Shape19.setTextureSize(128, 128);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
      this.setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    Shape1.render(par7);
    Shape2.render(par7);
    Shape3.render(par7);
    Shape4.render(par7);
    Shape5.render(par7);
    Shape6.render(par7);
    Shape7.render(par7);
    Shape8.render(par7);
    Shape9.render(par7);
    Shape10.render(par7);
    Shape11.render(par7);
    Shape12.render(par7);
    Shape13.render(par7);
    Shape14.render(par7);
    Shape15.render(par7);
    Shape16.render(par7);
    Shape17.render(par7);
    Shape18.render(par7);
    Shape19.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    //super.setRotationAngles(f, f1, f2, f3, f4, f5);
	  this.Shape9.rotateAngleY = par4 / (180F / (float)Math.PI);
      //this.Shape9.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape10.rotateAngleY = par4 / (180F / (float)Math.PI);
      //this.Shape10.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape11.rotateAngleY = par4 / (180F / (float)Math.PI);
      //this.Shape11.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape12.rotateAngleY = par4 / (180F / (float)Math.PI);
      //this.Shape12.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape13.rotateAngleY = par4 / (180F / (float)Math.PI);
      //this.Shape13.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape14.rotateAngleY = par4 / (180F / (float)Math.PI);
      //this.Shape14.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape15.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Shape15.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape16.rotateAngleY = par4 / (180F / (float)Math.PI);
      //this.Shape16.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape17.rotateAngleY = par4 / (180F / (float)Math.PI);
      //this.Shape17.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape18.rotateAngleY = par4 / (180F / (float)Math.PI);
      //this.Shape18.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape19.rotateAngleY = par4 / (180F / (float)Math.PI);
      //this.Shape19.rotateAngleX = par5 / (180F / (float)Math.PI);
  }

}
