// Date: 2014/06/29 11:03:55
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package hmggvcmob.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class GVCModelHeli extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape26;
  
  public GVCModelHeli()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 14, 14, 16);
      Shape1.setRotationPoint(-7F, 7F, -8F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 33);
      Shape2.addBox(0F, 0F, 0F, 6, 1, 1);
      Shape2.setRotationPoint(7F, 20F, -6F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0.5235988F);
      Shape3 = new ModelRenderer(this, 0, 33);
      Shape3.addBox(0F, 0F, 0F, 6, 1, 1);
      Shape3.setRotationPoint(7F, 20F, 4F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0.5235988F);
      Shape4 = new ModelRenderer(this, 0, 36);
      Shape4.addBox(0F, 0F, 0F, 1, 1, 22);
      Shape4.setRotationPoint(11F, 23F, -12F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 33);
      Shape5.addBox(0F, 0F, 0F, 6, 1, 1);
      Shape5.setRotationPoint(-12F, 23F, -6F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, -0.5235988F);
      Shape6 = new ModelRenderer(this, 0, 33);
      Shape6.addBox(0F, 0F, 0F, 6, 1, 1);
      Shape6.setRotationPoint(-12F, 23F, 4F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, -0.5235988F);
      Shape7 = new ModelRenderer(this, 0, 36);
      Shape7.addBox(0F, 0F, 0F, 1, 1, 22);
      Shape7.setRotationPoint(-12F, 23F, -12F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 61);
      Shape8.addBox(0F, 0F, 0F, 4, 4, 13);
      Shape8.setRotationPoint(-2F, 7F, 8F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 35, 60);
      Shape9.addBox(0F, 0F, 0F, 2, 2, 12);
      Shape9.setRotationPoint(-1F, 7F, 21F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 47, 46);
      Shape10.addBox(0F, 0F, 0F, 1, 6, 6);
      Shape10.setRotationPoint(1F, 5F, 29F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 47, 35);
      Shape11.addBox(0F, 0F, 0F, 2, 5, 1);
      Shape11.setRotationPoint(-1F, 2F, 32F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 44, 75);
      Shape12.addBox(0F, 0F, 0F, 8, 1, 2);
      Shape12.setRotationPoint(-4F, 1F, 32F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 0, 80);
      Shape13.addBox(0F, 0F, 0F, 8, 4, 8);
      Shape13.setRotationPoint(-4F, 3F, -2F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 0, 95);
      Shape14.addBox(0F, 0F, -1F, 24, 1, 2);
      Shape14.setRotationPoint(0F, 2F, 0F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 0, 95);
      Shape15.addBox(-24F, 0F, -1F, 24, 1, 2);
      Shape15.setRotationPoint(0F, 2F, 0F);
      Shape15.setTextureSize(64, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 0, 99);
      Shape16.addBox(-1F, 0F, 0F, 2, 1, 24);
      Shape16.setRotationPoint(0F, 2F, 0F);
      Shape16.setTextureSize(64, 32);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 0, 99);
      Shape17.addBox(-1F, 0F, -24F, 2, 1, 24);
      Shape17.setRotationPoint(0F, 2F, 0F);
      Shape17.setTextureSize(64, 32);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 36, 80);
      Shape18.addBox(0F, 0F, 0F, 10, 1, 3);
      Shape18.setRotationPoint(7F, 16F, 0F);
      Shape18.setTextureSize(64, 32);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 36, 80);
      Shape19.addBox(0F, 0F, 0F, 10, 1, 3);
      Shape19.setRotationPoint(-17F, 16F, 0F);
      Shape19.setTextureSize(64, 32);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 40, 99);
      Shape20.addBox(0F, 0F, 0F, 3, 3, 9);
      Shape20.setRotationPoint(14F, 17F, -3F);
      Shape20.setTextureSize(64, 32);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 40, 99);
      Shape21.addBox(0F, 0F, 0F, 3, 3, 9);
      Shape21.setRotationPoint(-17F, 17F, -3F);
      Shape21.setTextureSize(64, 32);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 0, 0);
      Shape22.addBox(-1F, 0F, -26F, 2, 1, 2);
      Shape22.setRotationPoint(0F, 2F, 0F);
      Shape22.setTextureSize(64, 32);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 0, 0);
      Shape23.addBox(-1F, 0F, 24F, 2, 1, 2);
      Shape23.setRotationPoint(0F, 2F, 0F);
      Shape23.setTextureSize(64, 32);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24 = new ModelRenderer(this, 0, 0);
      Shape24.addBox(-26F, 0F, -1F, 2, 1, 2);
      Shape24.setRotationPoint(0F, 2F, 0F);
      Shape24.setTextureSize(64, 32);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
      Shape25 = new ModelRenderer(this, 0, 0);
      Shape25.addBox(24F, 0F, -1F, 2, 1, 2);
      Shape25.setRotationPoint(0F, 2F, 0F);
      Shape25.setTextureSize(64, 32);
      Shape25.mirror = true;
      setRotation(Shape25, 0F, 0F, 0F);
      Shape26 = new ModelRenderer(this, 0, 0);
      Shape26.addBox(-1F, 0F, -1F, 2, 1, 2);
      Shape26.setRotationPoint(0F, 2F, 0F);
      Shape26.setTextureSize(64, 128);
      Shape26.mirror = true;
      setRotation(Shape26, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape26.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
