// Date: 2018/08/13 1:46:20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package hmggvcmob.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class ModelParachute extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer drag1;
    ModelRenderer drag2;
    ModelRenderer drag3;
    ModelRenderer drag4;
    ModelRenderer drag5;
    ModelRenderer seat;
  
  public ModelParachute()
  {
    textureWidth = 64;
    textureHeight = 32;
    GL11.glTranslatef(0,-1,0);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, -1F, 1, 30, 1);
      Shape1.setRotationPoint(-20F, -7F, 10F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, -0.2268928F, 0F, -0.5235988F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 1, 30, 1);
      Shape2.setRotationPoint(-20F, -7F, -10F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0.2268928F, 0F, -0.5235988F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(-1F, 0F, -1F, 1, 30, 1);
      Shape3.setRotationPoint(20F, -7F, 10F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, -0.2268928F, 0F, 0.5235988F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(-1F, 0F, 0F, 1, 30, 1);
      Shape4.setRotationPoint(20F, -7F, -10F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0.2268928F, 0F, 0.5235988F);
      drag1 = new ModelRenderer(this, 4, 0);
      drag1.addBox(0F, 0F, 0F, 10, 1, 20);
      drag1.setRotationPoint(12F, -11F, -10F);
      drag1.setTextureSize(64, 32);
      drag1.mirror = true;
      setRotation(drag1, 0.0174533F, 0F, 0.418879F);
      drag2 = new ModelRenderer(this, 4, 0);
      drag2.addBox(0F, 0F, 0F, 10, 1, 20);
      drag2.setRotationPoint(3F, -13F, -10F);
      drag2.setTextureSize(64, 32);
      drag2.mirror = true;
      setRotation(drag2, 0.0174533F, 0F, 0.2268928F);
      drag3 = new ModelRenderer(this, 4, 0);
      drag3.addBox(0F, 0F, 0F, 6, 1, 20);
      drag3.setRotationPoint(-3F, -13F, -10F);
      drag3.setTextureSize(64, 32);
      drag3.mirror = true;
      setRotation(drag3, 0.0174533F, 0F, 0F);
      drag4 = new ModelRenderer(this, 4, 0);
      drag4.addBox(-10F, 0F, 0F, 10, 1, 20);
      drag4.setRotationPoint(-3F, -13F, -10F);
      drag4.setTextureSize(64, 32);
      drag4.mirror = true;
      setRotation(drag4, 0.0174533F, 0F, -0.2268928F);
      drag5 = new ModelRenderer(this, 4, 0);
      drag5.addBox(-10F, 0F, 0F, 10, 1, 20);
      drag5.setRotationPoint(-12F, -11F, -10F);
      drag5.setTextureSize(64, 32);
      drag5.mirror = true;
      setRotation(drag5, 0.0174533F, 0F, -0.418879F);
      seat = new ModelRenderer(this, 4, 21);
      seat.addBox(0F, 0F, 0F, 10, 3, 8);
      seat.setRotationPoint(-5F, 18F, -4F);
      seat.setTextureSize(64, 32);
      seat.mirror = true;
      setRotation(seat, 0.0174533F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    drag1.render(f5);
    drag2.render(f5);
    drag3.render(f5);
    drag4.render(f5);
    drag5.render(f5);
    seat.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
